// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import Flatpickr from "stimulus-flatpickr";
// import "flatpickr/dist/flatpickr.min.css";
application.register("flatpickr", Flatpickr);

